### ISSUE TITLE
Indian samples in the B1.1.7 clade

### ISSUE THREAD

**Issue by fohristiwhirl** [emmahodcroft/covariants#7]
Sorry to bother you, I suppose this isn't how you prefer to be contacted. But what's the story with the two samples from India in your B1.1.7 tree at https://nextstrain.org/groups/neherlab/ncov/S.N501?c=gt-S_501,69

I mean specifically these ones:

![image](https://user-images.githubusercontent.com/16438795/103458286-67b12980-4cfe-11eb-9eb2-2c9499de91fd.png)

By the colours, they don't have the 69/70 deletion **[edit: I see they do have N501Y however]**, so their position there doesn't make sense to me. Are they there because the rest of their genome is similar to B1.1.7?

If yes, what would cause this? Coincidence? Lab mistake? Recombination?

**Comment by fohristiwhirl** [comment]
I wrote initially that N501Y is not present; I see that it is, so I have corrected the comment.

**Comment by emmahodcroft** [comment]
Thanks @fohristiwhirl ! This is a good question. The sequences do have N501Y, as you corrected. They do not seem to have the deletion in the sequence, but we should probably be cautious in interpreting this. Gaps/deletions can cause problems both with sequencing and with mapping, and my guess would be that there's been an error in one of these. The rest of the genome does seem to put the sequences within this cluster quite solidly, so I think these likely are members of the 501Y.V2 variant, but have had some issues with the gaps.
